name: 'Lint And Quality Check'

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions: read-all

jobs:
  quality-check:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci
      - name: Lint Repository
        run: npm run lint
  vulnerability-check:
    name: Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check For Vulnerabilities
        uses: bridgecrewio/checkov-action@v12
